name: CI

on: [push]

jobs:
  build:

    runs-on: ubuntu-latest
    
    steps:
    - uses: actions/checkout@v1
    - name: Run a one-line script
      run: echo Hello, world!
    - name: Run a multi-line script
      run: |
        echo Add other actions to build,
        echo test, and deploy your project.
        ls .
        git checkout master
        git config user.name "${GITHUB_ACTOR}"
        git config user.email "${GITHUB_ACTOR}@users.noreply.github.com"
        remote_repo="https://${GITHUB_ACTOR}:${{ secrets.GITHUB_TOKEN }}@github.com/${GITHUB_REPOSITORY}.git"
        git remote rm origin || true
        git remote add origin "${remote_repo}"
        git clone https://github.com/mathblogging/mathblogging-base.git
        cd mathblogging-base
        mkdir mathblogging.org
        mkdir feeds
        npm i
        node ./tools/csv_to_json.js
        sh ./tools/wgetter.sh 
        node ./lib/generateEntries.js
        sed -i '29d' lib/app.js
        node ./lib/app.js
        mv mathblogging.org ../docs
        cd ..
        git add docs
        git commit -m'generated site'
        git push origin master
